name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache

      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/huniangitb/android_gki_kernel_5.10_common
          kernel-branch: android12-5.10-2025-09
          config: gki_defconfig
          arch: arm64
          aosp-gcc: true
          ccache: true
          ksu: false
          rekernel: false
          
          android-version: 12
          other-clang-url: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/mirror-goog-llvm-r596125-release/clang-r584948b.tar.gz
          anykernel3: true

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: /home/runner/work/kernel_build_action/kernel_build_action/kernel/kernel/out/arch/arm64/boot/Image
          if-no-files-found: error
          retention-days: 30
