# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/huniangitb/android_gki_kernel_5.10_common
          kernel-branch: android12-5.10-2025-09
          config: gki_defconfig
          arch: arm64
          aosp-clang: true
          android-version: 15
          aosp-clang-version: r522817
          anykernel3: true
