# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/huniangitb/android_gki_kernel_5.10_common
          kernel-branch: android12-5.10-2025-09
          config: gki_defconfig
          arch: arm64
          aosp-gcc: true
          
          android-version: 12
          other-clang-url: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/70a12c4fe88940ab2b0e6d763492dffa2f07e15a/clang-r547379.tar.gz
          anykernel3: true
